# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://gitea.sunbury.xyz/lucabecker/pre-commit
      rev: v0.0.1
      hooks:
          - id: ts-no-console-log
          - id: ts-no-focus-test
