name: Cursor Code Review

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    code-review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        env:
            CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Install Cursor CLI
              if: ${{ env.CURSOR_API_KEY != '' }}
              run: |
                  curl https://cursor.com/install -fsS | bash
                  echo "$HOME/.cursor/bin" >> "$GITHUB_PATH"

            - name: Perform code review
              if: ${{ env.CURSOR_API_KEY != '' }}
              timeout-minutes: 10
              env:
                  GH_TOKEN: ${{ github.token }}
                  MODEL: sonnet-4.5-thinking
              run: |
                  cursor-agent --force --model "$MODEL" --output-format=text --print "You are operating in a GitHub Actions runner performing automated code review. The gh CLI is available and authenticated via GH_TOKEN. You may comment on pull requests.

                  Context:
                  - Repo: ${{ github.repository }}
                  - PR Number: ${{ github.event.pull_request.number }}
                  - PR Head SHA: ${{ github.event.pull_request.head.sha }}
                  - PR Base SHA: ${{ github.event.pull_request.base.sha }}

                  Objectives:
                  1) Re-check existing review comments and reply resolved when addressed
                  2) Review the current PR diff and flag only clear, high-severity issues
                  3) Leave very short inline comments (1-2 sentences) on changed lines only and a brief summary at the end

                  Procedure:
                  - Get existing comments: gh pr view --json comments,reviews
                  - Get diff: gh pr diff
                  - If a previously reported issue appears fixed by nearby changes, reply: ✅ This issue appears to be resolved by the recent changes
                  - Avoid duplicates: skip if similar feedback already exists on or near the same lines

                  Commenting rules:
                  - Max 10 inline comments total; prioritize the most critical issues
                  - One issue per comment; place on the exact changed line
                  - Natural tone, specific and actionable; do not mention automated or high-confidence
                  - Use emojis: 🚨 Critical 🔒 Security ⚡ Performance ⚠️ Logic ✅ Resolved ✨ Improvement

                  Focus areas for this TypeScript/Homebridge project:
                  - Homebridge API compatibility and best practices
                  - TypeScript type safety and proper interfaces
                  - Error handling and logging patterns
                  - Configuration validation with Zod
                  - HTTP server security and validation
                  - Memory leaks and resource management
                  - Network error handling and retries

                  Submission:
                  - Submit one review containing inline comments plus a concise summary
                  - Use only: gh pr review --comment
                  - Do not use: gh pr review --approve or --request-changes"
