name: OpenCode Review

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    code-review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install OpenCode CLI
              run: npm install -g opencode-ai

            - name: Perform code review
              timeout-minutes: 10
              env:
                  GH_TOKEN: ${{ github.token }}
                  LITELLM_API_KEY: ${{ secrets.LITELLM_API_KEY }}
                  LITELLM_ENDPOINT: ${{ secrets.LITELLM_ENDPOINT }}
              run: |
                  opencode run --model litellm/anthropic/claude-sonnet-4-5 "You are operating in a GitHub Actions runner performing automated code review. The gh CLI is available and authenticated via GH_TOKEN. You may comment on pull requests.

                  Context:
                  - Repo: ${{ github.repository }}
                  - PR Number: ${{ github.event.pull_request.number }}
                  - PR Head SHA: ${{ github.event.pull_request.head.sha }}
                  - PR Base SHA: ${{ github.event.pull_request.base.sha }}

                  Objectives:
                  1) Re-check existing review comments and resolve them when issues are addressed
                  2) Review the current PR diff and flag only clear, high-severity issues
                  3) Leave very short inline comments (1-2 sentences) on changed lines only and a brief summary at the end

                  Procedure:
                  - Get existing comments: gh pr view --json comments,reviews
                  - Get diff: gh pr diff
                  - Read related files when you deem the information valuable for context (imports, dependencies, types, etc.)
                  - If a previously reported issue appears fixed by nearby changes:
                    * Reply with: ✅ This issue appears to be resolved by the recent changes
                    * Resolve the conversation using: gh pr comment <comment-id> --resolve
                  - Avoid duplicates: skip if similar feedback already exists on or near the same lines

                  Commenting rules:
                  - Max 10 inline comments total; prioritize the most critical issues
                  - One issue per comment; place on the exact changed line
                  - Natural tone, specific and actionable; do not mention automated or high-confidence
                  - Use emojis: 🚨 Critical 🔒 Security ⚡ Performance ⚠️ Logic ✅ Resolved ✨ Improvement

                  Focus areas for this TypeScript/Homebridge project:
                  - Homebridge API compatibility and best practices
                  - TypeScript type safety and proper interfaces
                  - Error handling and logging patterns
                  - Configuration validation with Zod
                  - HTTP server security and validation
                  - Memory leaks and resource management
                  - Network error handling and retries

                  Submission:
                  - Submit one review containing inline comments plus a concise summary
                  - Use: gh pr review --comment for new reviews
                  - Use: gh pr comment <comment-id> --resolve to resolve addressed issues
                  - Do not use: gh pr review --approve or --request-changes"
